services:
  postgres:
    image: postgres:14.2-alpine
    networks:
      postgres-database:
        aliases:
          - database
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 4s
      timeout: 2s
      retries: 5
  database-migrations:
    image: migrate/migrate
    networks:
      - postgres-database
    volumes:
      - ./src/framework/migrations:/migrations
    command: [
      "-path", "migrations",
      "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
        condition: service_healthy
networks:
  postgres-database: